development:
  adapter: postgresql
  database: sheson_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sheson_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: seshon
  pool: 5
  timeout: 5000